name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Contributions
        uses: Platane/snk@master
        with:
          github_user_name: FrogInDizzy
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake Contribution Graph
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          mv dist/github-contribution-grid-snake-dark.svg output/
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add output/
          git commit -m "Generated Snake Contribution Graph" || echo "No changes to commit"
          git push origin main
