name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Contributions
        uses: Platane/snk@v2
        with:
          github_user_name: FrogInDizzy 
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Snake Contribution Graph
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add output/
          git commit -m "Generated Snake Contribution Graph" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
